version: '3.9'

services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    command: 'npm run start:dev'
    environment:
      dbUri: 'postgres://postgres:123456@db:5432/app'
    ports:
      - '8000:8000'
  hasura:
    image: hasura/graphql-engine:v2.16.1
    container_name: hasura
    depends_on:
      - db
    ports:
      - '8080:8080'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:123456@db:5432/app
      HASURA_GRAPHQL_ADMIN_SECRET: youradminsecretkey
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # enable GraphQL console
    volumes:
      - ./hasura_metadata_2024_06_23_03_09_01_420.json:/hasura-metadata/hasura_metadata.json
volumes:
  postgres_data:
