name: node-ddd

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Setup Node.js
       uses: actions/setup-node@v3
       with:
        node-version: '21'
     - name: Install node_modules
       run: npm install
     - name: Run tests
       run: npm run test
     - name: build project
       run: npm run build